old_perSite/config/routes.rb
Rails.application.routes.draw do
  
  root "castles#road"
  get "road" => "castles#road"
  get "courtyard" => "castles#courtyard"

  # sessions
  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  delete 'logout' => "sessions#destroy"
  resources :users

  get "gallery" => "paintings#index"
  resources :paintings
  
  get "study" => "posts#index"
  resources :posts

  get "gameRoom" => "castles#gameRoom"
  # need back end for program games

  get "workshop" => "projects#index"
  # need back end for idea-incubator
end

old_perSite/app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :owner, class_name: :"User"

  validates :owner, presence: true
  validates :image, presence: true

  mount_uploader :image, PictureUploader
end

old_perSite/app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :author, class_name: :"User"

	validates :author, presence: true
end

old_perSite/app/models/user.rb
class User < ActiveRecord::Base

	validates :username, presence: true, uniqueness: true

	has_many :posts, foreign_key: :author_id
	has_many :paintings, foreign_key: :owner_id


	def password
		@password ||= BCrypt::Password.new(password_digest)
	end

	def password=(new_password)
		@password = BCrypt::Password.create(new_password)
		self.password_digest = @password
	end

	def authenticate?(pword)
		password == pword
	end

	def owns?(object)
		id == object.id
	end
end

old_perSite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

old_perSite/app/controllers/castles_controller.rb
class CastlesController < ApplicationController
	layout "castle"

	# def index
	# end

	def road
	end

	def courtyard
	end

	def gameRoom
	end

	# def show
	# end

	# def edit
	# end

	# def update
	# end

	# def destroy
	# end

end

old_perSite/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.new(painting_params)
    @painting.owner = current_user
    if @painting.save
      redirect_to painting_path(@painting)
    else
      render "new"
    end
  end

  def show
    @painting = Painting.find_by_id(params[:id])
  end

  def edit
    @painting = current_user.paintings.find_by_id(params[:id])
  end

  def destroy
    painting = current_user.paintings.find_by_id(params[:id])
    painting.destroy if painting
    redirect_to paintings_path
  end

  def index
    @paintings = Painting.all
  end

  private
  def painting_params
    params.require(:painting).permit(:artist_name, :description, :aquisition_date, :image, :title)
  end
end

old_perSite/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.author = current_user
		if @post.save
			redirect_to post_path(@post)
		else
			render "new"
		end
	end

	def show
		@post = Post.includes(:author).find_by_id(params[:id])
	end

	def edit
		@post = Post.find_by_id(params[:id])
		redirect_to post_path(@post) unless current_user && current_user.owns?(@post)
	end

	def update
		@post = current_user.posts.find_by_id(params[:id]) if current_user
		if @post && @post.save
			redirect_to post_path(@post)
		else
			@error_object = @post
			render "edit"
		end
		
	end

	def destroy
		post = current_user.posts.find_by_id(params[:id])
		post.destroy if post
		redirect_to posts_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :body)
	end

end

old_perSite/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(username: params[:session][:username])
		if user && user.authenticate?(params[:session][:password])
			log_in user
			redirect_to courtyard_path
		else
			@errors = ["Bad username - password combination"]
			render 'new'
		end
	end

	def destroy
		log_out
		redirect_to root_url
	end
end

old_perSite/app/controllers/users_controller.rb
class UsersController < ApplicationController

	# def index
	# end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_path
		else
			render "new"
		end
	end
	
	def show
		@user = current_user
	end

	# def edit
	# end

	# def update
	# end

	# def destroy
	# end

	private
	def user_params
		params.require(:user).permit(:username, :password)
	end

end

old_perSite/app/helpers/application_helper.rb
module ApplicationHelper
	include SessionsHelper
  include PostsHelper
end

old_perSite/app/helpers/posts_helper.rb
module PostsHelper
end

old_perSite/app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		else
			nil
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

end

old_perSite/app/views/castles/_menu_buttons.html.erb
<li class='menu-list-item'>
  <%= link_to "castle road", road_path, :class => "menu-btn" %>
</li>  
<li class='menu-list-item'>
  <%= link_to "courtyard", courtyard_path, :class => "menu-btn" %>
</li>  

old_perSite/app/views/castles/courtyard.html.erb
<%= render partial: "sharedPartials/tab_text", locals: {text: "Courtyard"} %>

<div class="container">
  <ul>
    <li><%= link_to "game room", gameRoom_path %></li>
    <li><%= link_to "road", road_path %></li>
    <li><%= link_to "gallery", gallery_path %></li>
    <li><%= link_to "study", study_path %></li>
    
  </ul>
</div>

old_perSite/app/views/castles/gameRoom.html.erb
<div class='container'>
  <p>made it to the secret page</p>

</div>

<%= javascript_include_tag "castle.js" %>

old_perSite/app/views/castles/road.html.erb
<div id='splash-book-container'>
  <div class="book-item" id='splash-book-picture'>
    <%= link_to image_tag('pc_trees_forest.jpg'), courtyard_path %>
  </div>
  <div class="book-item" id='splash-book-text'>
    <p><span class='lead-character'><%= link_to "I", login_path %></span> always had an active imagination when I was a child, but the stories and worlds I lost myself in never lasted past my departure to sleep.  As I grew older I learned of a construct called a memmory castle, by which people could organize the world as it fell before their mind's eye, but by then I was already so much a tramp as to feel constrained by such a fixed structure.  However as I learn the ways of technological artistry a new path opened before me, a construct wrought not from myself but from the imaginary material of cyber-space.  Herein might I find the utility and diversion equal to that of any memory castle, and manyfold the pleasure since such comes from sharing the experience of the creation, and all without offending my good-trampish-sensibilities by commiting to some doctrine or rigid point of view.</p>
    <p><span class='lead-character'>I</span>f you are curious to see as i see please proceed along the path, through a portal as it were, to a castle of some delight and curiosity.</p>
  </div>
</div>

old_perSite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <%= yield :head %>
	  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<div id='default-page-layout'>
			<%= render partial: "sharedPartials/menu_bar", 
				locals:{pg: @page || nil, op: @options || []} %>
			<%= yield %>
		</div>
	</body>

</html>

old_perSite/app/views/layouts/castle.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :head %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id='splash-page-layout'>
      <%= yield %>
    </div>
  </body>

</html>

old_perSite/app/views/paintings/_menu_buttons.html.erb
<li class='menu-list-item'>
  <%= link_to "gallery", paintings_path, :class => "menu-btn" %>
</li>

<% if logged_in? %>
  <li class='menu-list-item'>
    <%= link_to "new painting", new_painting_path, :class => "menu-btn" %>
  </li>
<% end %>

old_perSite/app/views/paintings/_painting_form_fields.html.erb
<%= f.label :artist_name %>
<%= f.text_field :artist_name %>
<br>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<%= f.label :aquisition_date %>
<%= f.date_field :aquisition_date %>
<br>
<%= f.label :description %>
<%= f.text_area :description %>
<br>
<%= f.file_field :image %>
<br>

old_perSite/app/views/paintings/edit.html.erb
<%= render partial: "sharedPartials/tab_text", locals: {text: "Gallary"} %>

<%= render partial: "sharedPartials/menu_bar"

<div class='container'>
  <%= render partial: "sharedPartials/object_errors", locals: {brokenObject: @painting} %>
  <%= form_for @painting do |form| %>
    <%= render partial: "painting_form_fields", locals: {f: form} %>
    <%= form.submit "edit" %>
  <% end %>
</div>

old_perSite/app/views/paintings/index.html.erb
<%= render partial: "sharedPartials/tab_text", locals: {text: "Gallary"} %>

<div class='container'>
  <h2 class="section-title">Paintings index</h2>

  <ul id='painting-list'>
    <% @paintings.each do |painting| %>
      <li class='painting-title'>
        <%= link_to image_tag(painting.image_url(:thumb).to_s), painting %>
        <%=  "- #{painting.title}" %>
      </li>
    <% end %>
  </ul>
</div>

old_perSite/app/views/paintings/new.html.erb
<%= render partial: "sharedPartials/tab_text", locals: {text: "Gallary"} %>

<div class='container'>
  <%= render partial: "sharedPartials/object_errors", locals: {brokenObject: @painting} %>
  <%= form_for @painting do |form| %>
    <%= render partial: "painting_form_fields", locals: {f: form} %>
    <%= form.submit "add" %>
  <% end %>
</div>

old_perSite/app/views/paintings/show.html.erb
<%= render partial: "sharedPartials/tab_text", locals: {text: "Gallary"} %>

<div class='container'>
  <%= image_tag @painting.image_url(:portrait).to_s if @painting.image_url(:portrait).to_s%>
  <p><%= @painting.title %> by <%=@painting.artist_name%></p>

</div>

old_perSite/app/views/posts/_menu_buttons.html.erb
<li class='menu-list-item'>
  <%= link_to "study", posts_path, :class => "menu-btn" %>
</li>

<% if logged_in? %>
  <li class='menu-list-item'>
    <%= link_to "new post", new_post_path, :class => "menu-btn" %>
  </li>
<% end %>

old_perSite/app/views/posts/_post_form_fields.html.erb
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<%= f.label :body %>
<%= f.text_area :body %>
<br>

old_perSite/app/views/posts/edit.html.erb
<%= render partial: "sharedPartials/tab_text", locals: {text: "Posts"} %>

<div class='container'>
	<%= render partial: "sharedPartials/object_errors", 
    locals: {brokenObject: @error_object} %>
	<%= form_for @post do |form| %>
		<%= render partial: "post_form_fields", locals: {f: form} %>
		<%= form.submit "edit" %>
	<% end %>
</div>

old_perSite/app/views/posts/index.html.erb
<%= render partial: "sharedPartials/tab_text", locals: {text: "Posts"} %>

<div class='container'>
	<h2 class="section-title">Post index</h2>

	<ul id='post-list'>
		<% @posts.each do |post| %>
			<li class='post-title'>
        <%= link_to "#{post.title}", post %>
        <% if current_user && current_user.owns?(post) %>
          <%= link_to " edit,", edit_post_path(post) %>
          <%= link_to " nuke", post, method: :delete %>
        <% end %>
      </li>
		<% end %>
	</ul>
</div>

old_perSite/app/views/posts/new.html.erb
<%= render partial: "sharedPartials/tab_text", locals: {text: "Posts"} %>

<div class='container'>
	<%= render partial: "sharedPartials/object_errors", locals: {brokenObject: @post} %>
	<%= form_for @post do |form| %>
		<%= render partial: "post_form_fields", locals: {f: form} %>
		<%= form.submit "create" %>
	<% end %>
</div>

old_perSite/app/views/posts/show.html.erb
<%= render partial: "sharedPartials/tab_text", locals: {text: "Posts"} %>

<div class='container'>
  <%= render partial: "sharedPartials/object_errors", 
    locals: {brokenObject: @error_object} %>
  <h3><%= @post.title %></h3>
  <p>by <%=@post.author.username%></p>
  <br>
  <p> <%= @post.body %></p>

</div>

old_perSite/app/views/sharedPartials/_error_box.html.erb
<% if errors && errors.any? %>
	<div class="error_box">
		<ul>
			<% errors.each do |error| %>
				<li><%= error %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

old_perSite/app/views/sharedPartials/_menu_bar.html.erb
<div id='menu-bar'>
	<ul id='menu-list'>
		<%= render partial: "castles/menu_buttons", locals: {page: pg, options: op} %>
		<%= render partial: "posts/menu_buttons", locals: {page: pg, options: op} %>
		<%= render partial: "paintings/menu_buttons", locals: {page: pg, options: op} %>
		<%= render partial: "users/menu_buttons", locals: {page: pg, options: op} %>
		<%= render partial: "sessions/menu_buttons", locals: {page: pg, options: op} %>
	</ul>
</div>

old_perSite/app/views/sharedPartials/_menu_options.html.erb
<% content_for :menu_options do %>
  
<% end %>

old_perSite/app/views/sharedPartials/_object_errors.html.erb
<% if brokenObject && brokenObject.errors.any? %>
  <%= render partial: "sharedPartials/error_box", 
    locals: {errors: brokenObject.errors.full_messages} %>
<% end %>

old_perSite/app/views/sharedPartials/_side_bar.html.erb
<!-- <div class='side-bar'>
	<ul>
		<% i = 0 %>
		<% while i < 5 do %>
			<li><%#= "this is bullet #{i}"%></li>
			<% i = i + 1 %>
		<% end %>
	</ul>
</div> -->

<ul class='side-bar'>
	<% i = 0 %>
	<% while i < 5 do %>
		<li><%= "this is bullet #{i}"%></li>
		<% i = i + 1 %>
	<% end %>
</ul>

old_perSite/app/views/sharedPartials/_tab_text.html.erb
<% content_for :head do %>
	<title><%= text %></title>
<% end %>

old_perSite/app/views/users/_menu_buttons.html.erb
<% if !logged_in? %>
  <li class='menu-list-item'>
    <%= link_to "new user", new_user_path, :class => "menu-btn" %>
  </li>
<% end %>

old_perSite/app/views/users/_user_form_fields.html.erb
<div class="field">
	<%= f.label :username %>
	<%= f.text_field :username %>
</div>
<div class="field">
	<%= f.label :password %>
	<%= f.password_field :password %>
</div>
<div class="field">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
</div>

old_perSite/app/views/users/new.html.erb
<%= render partial: "sharedPartials/tab_text", locals: {text: "Sign Up"} %>

<div class='container'>
	<h1> Sign Up</h1>
	<%= render partial: "sharedPartials/object_errors", locals: {brokenObject: @user} %>

	<%= form_for @user do |form| %>
		<%= render partial: "user_form_fields", locals: {f: form} %>
		<div class="actions"><%= form.submit %></div>
	<% end %>
</div>